FROM alpine:latest

ENV TZ=Asia/Shanghai
RUN apk update
RUN apk add tzdata && \
    cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app
COPY go-cqhttp-linux-v1.0.0.rc .
RUN chmod +x go-cqhttp

WORKDIR /data

ENTRYPOINT exec /app/go-cqhttp faststart