FROM node:16.14.2-alpine3.15
ENV TZ=Asia/Shanghai
RUN apk update
RUN apk add tzdata && \
    cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app
RUN apk add --update --no-cache \
    make \
    g++ \
    jpeg-dev \
    cairo-dev \
    giflib-dev \
    pango-dev \
    libtool \
    autoconf \
    automake

COPY xkbot/package.json .
RUN npm install
COPY xkbot .
ENTRYPOINT npm run start



